### ISSUE TITLE
Feature Suggestion: add relation with another Mongo Collection

### ISSUE THREAD

**Issue by psaussure** [fpetru/WebApiMongoDB#1]
## A simple suggestion
To make your tutorial the best and most up-to-date tutorial about Mongo and ASP.Core.

Could you explain how to create for example a User which can have associated notes. Here is a perfect example JSON:
```
Notes: {
  // Your Actual Notes Model
},
Users: {
  "Id": objectID,
  "email": "username@example.com",
  "notes": {
    Note1ObjectId: true,
    Note2ObjectId: true,
  }
}
```
And then show us how to list all notes from a given User Id.

I have always wanted to learn doing so and I can't find any tutorial covering this situation.

## Another missing thing in your tutorial
If Notes could contain another key/value pair, such as "Title": string what if I want to update only the Notes.title of a given Note?

**Comment by fpetru** [comment]
Hello,

Let me start with the second suggestion. 

To update one or more properties, but not the full document, please take a look to the function UpdateNote in the article [http://www.qappdesign.com/using-mongodb-with-net-core-webapi/](http://www.qappdesign.com/using-mongodb-with-net-core-webapi/).

`public async Task<UpdateResult> UpdateNote(string id, string body)`

In your case the code would be:

```
var filter = Builders<Note>.Filter.Eq(s => s.Id, id);
var update = Builders<Note>.Update.Set(s => s.Title, "sample value");
await _context.Notes.UpdateOneAsync(filter, update);
```

Returning to the first suggestion, I am wondering if you wanted to share the notes between users. What would be your actual case, just in few words (no json or code) ?

Thanks
Petru

**Comment by psaussure** [comment]
Hi and thanks for answer!

First, about update, it seems it accepts only body as second argument. What if I want to change any other data, with an undefined type. For example I could have isPublished: bool. Then I can't use really your function and I struggle putting a sufficiently generic second argument to update only the data this argument refers to.

For the first suggestion, no, I just want a note to be the property of one user at the time. So I want to be able to simply retrieve all the noteID which belong to a given user (by listing each of his notes ObjectID in the "notes" node as described in the first post. And then be able to retrieve for example the title of notes or the isPublished state (not in your Model at the moment, but only a suggestion).

**Comment by fpetru** [comment]
Hi,

Please check my latest article on joining the collections.
http://www.qappdesign.com/mongodb-and-linq-how-to-aggregate-and-join-collections/

Best regards
Petru
