### ISSUE TITLE
INoteRepository is coupled to MongoDB

### ISSUE THREAD

**Issue by gehnster** [fpetru/WebApiMongoDB#2]
You use INoteRepository, which is great, but you still reference MongoDB within it for DeleteResult and UpdateResult. Shouldn't the interface be decoupled from MongoDB in case you want to switch to another NoSQL document-based implementation?

**Comment by fpetru** [comment]
Yes, this is true and I will fix soon this problem.

**Comment by fpetru** [comment]
Fixed
