### ISSUE TITLE
Sample MVC views

### ISSUE THREAD

**Issue by papyr** [fpetru/WebApiMongoDB#4]
Hi, can you please add some sample MVC views so we can expand on that

**Comment by fpetru** [comment]
Hi,

Please find here a full guide here: [Using MongoDB .NET Driver with ASP.NET Core MVC](https://www.qappdesign.com/mongodb-aspnetmvc-core/), and the [Github repository](https://github.com/fpetru/mongodb-aspnetmvc). 

Best regards,
Petru
